In [2]:
import pandas as pd

In [7]:
df = pd.read_csv("data.txt")
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,84334,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Germany,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers,26.0,Man,No,Straight / Heterosexual,NaN,No,Too long,Easy
1,14662,I am a student who is learning to code,Yes,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Sri Lanka,"Yes, full-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers,20.0,Woman,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Neither easy nor difficult
2,3292,I am a student who is learning to code,No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Sweden,"Yes, part-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,25.0,Man,No,Straight / Heterosexual,Multiracial,No,Too long,Easy
3,36271,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United Kingdom,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,32292,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,23.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44436,8766,I code primarily as a hobby,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",Russian Federation,"Yes, part-time",Some college/university study without earning ...,Web development or web design,...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
44437,72435,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,40.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Easy
44438,34292,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,NaN,NaN,NaN,NaN,NaN,No,Too long,Easy
44439,14219,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Norway,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...",...,Just as welcome now as I felt last year,Tech meetups or events in your area,28.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
44440,64515,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,31.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy

In [8]:
df.shape

(44441, 85)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 44441 entries, 0 to 44440
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              44441 non-null  int64
 1   MainBranch              44152 non-null  str
 2   Hobbyist                44441 non-null  str
 3   OpenSourcer             44441 non-null  str
 4   OpenSource              43367 non-null  str
 5   Employment              43602 non-null  str
 6   Country                 44380 non-null  str
 7   Student                 43522 non-null  str
 8   EdLevel                 43256 non-null  str
 9   UndergradMajor          37923 non-null  str
 10  EduOther                42105 non-null  str
 11  OrgSize                 35991 non-null  str
 12  DevType                 40739 non-null  str
 13  YearsCode               43949 non-null  str
 14  Age1stCode              43803 non-null  str
 15  YearsCodePro            37227 non-null  str
 16  CareerSat               36480 non-null  str
 17  JobSat                  35589 non-null  str
 18  MgrIdiot                30716 non-null  str
 19  MgrMoney                30703 non-null  str
 20  MgrWant                 30747 non-null  str
 21  JobSeek                 40290 non-null  str
 22  LastHireDate            39936 non-null  str
 23  LastInt                 33661 non-null  str
 24  FizzBuzz                35767 non-null  str
 25  JobFactors              39715 non-null  str
 26  ResumeUpdate            38971 non-null  str
 27  CurrencySymbol          35783 non-null  str
 28  CurrencyDesc            35783 non-null  str
 29  CompTotal               28066 non-null  float64
 30  CompFreq                31772 non-null  str
 31  ConvertedComp           28019 non-null  float64
 32  WorkWeekHrs             32343 non-null  float64
 33  WorkPlan                34580 non-null  str
 34  WorkChallenge           34184 non-null  str
 35  WorkRemote              35256 non-null  str
 36  WorkLoc                 35140 non-null  str
 37  ImpSyn                  35962 non-null  str
 38  CodeRev                 35274 non-null  str
 39  CodeRevHrs              24887 non-null  float64
 40  UnitTests               31432 non-null  str
 41  PurchaseHow             30679 non-null  str
 42  PurchaseWhat            31113 non-null  str
 43  LanguageWorkedWith      43749 non-null  str
 44  LanguageDesireNextYear  42000 non-null  str
 45  DatabaseWorkedWith      37931 non-null  str
 46  DatabaseDesireNextYear  34528 non-null  str
 47  PlatformWorkedWith      40351 non-null  str
 48  PlatformDesireNextYear  38733 non-null  str
 49  WebFrameWorkedWith      32436 non-null  str
 50  WebFrameDesireNextYear  31475 non-null  str
 51  MiscTechWorkedWith      29719 non-null  str
 52  MiscTechDesireNextYear  32195 non-null  str
 53  DevEnviron              43625 non-null  str
 54  OpSys                   43905 non-null  str
 55  Containers              42670 non-null  str
 56  BlockchainOrg           24168 non-null  str
 57  BlockchainIs            30099 non-null  str
 58  BetterLife              43124 non-null  str
 59  ITperson                43573 non-null  str
 60  OffOn                   43348 non-null  str
 61  SocialMedia             42153 non-null  str
 62  Extraversion            43651 non-null  str
 63  ScreenName              40243 non-null  str
 64  SOVisit1st              41931 non-null  str
 65  SOVisitFreq             44139 non-null  str
 66  SOVisitTo               44057 non-null  str
 67  SOFindAnswer            43916 non-null  str
 68  SOTimeSaved             43159 non-null  str
 69  SOHowMuchTime           34279 non-null  str
 70  SOAccount               43924 non-null  str
 71  SOPartFreq              37383 non-null  str
 72  SOJobs                  44028 non-null  str
 73  EntTeams                43914 non-null  str
 74  SOComm                  44053 non-null  str
 75  WelcomeChange           42911 non-null  str
 76  SONewContent            34834 non-null  str
 77  Age                     39613 non-null  float64
 78  Gender                  42698 non-null  str
 79  Trans                   41790 non-null  str
 80  Sexuality               38019 non-null  str
 81  Ethnicity               38322 non-null  str
 82  Dependents              41562 non-null  str
 83  SurveyLength            43479 non-null  str
 84  SurveyEase              43543 non-null  str
dtypes: float64(5), int64(1), str(79)
memory usage: 28.8 MB

In [11]:
pd.set_option("display.max_columns",85)
pd.set_option("display.max_rows",85)

In [12]:
schema_df = pd.read_csv("schema.txt")
schema_df

                    Column                                       QuestionText
0               Respondent  Randomized respondent ID number (not in order ...
1               MainBranch  Which of the following options best describes ...
2                 Hobbyist                            Do you code as a hobby?
3              OpenSourcer        How often do you contribute to open source?
4               OpenSource  How do you feel about the quality of open sour...
5               Employment  Which of the following best describes your cur...
6                  Country          In which country do you currently reside?
7                  Student  Are you currently enrolled in a formal, degree...
8                  EdLevel  Which of the following best describes the high...
9           UndergradMajor  What was your main or most important field of ...
10                EduOther  Which of the following types of non-degree edu...
11                 OrgSize  Approximately how many people are employed by ...
12                 DevType  Which of the following describe you? Please se...
13               YearsCode  Including any education, how many years have y...
14              Age1stCode  At what age did you write your first line of c...
15            YearsCodePro  How many years have you coded professionally (...
16               CareerSat  Overall, how satisfied are you with your caree...
17                  JobSat  How satisfied are you with your current job? (...
18                MgrIdiot  How confident are you that your manager knows ...
19                MgrMoney  Do you believe that you need to be a manager t...
20                 MgrWant  Do you want to become a manager yourself in th...
21                 JobSeek  Which of the following best describes your cur...
22            LastHireDate  When was the last time that you took a job wit...
23                 LastInt  In your most recent successful job interview (...
24                FizzBuzz  Have you ever been asked to solve FizzBuzz in ...
25              JobFactors  Imagine that you are deciding between two job ...
26            ResumeUpdate  Think back to the last time you updated your r...
27          CurrencySymbol  Which currency do you use day-to-day? If your ...
28            CurrencyDesc  Which currency do you use day-to-day? If your ...
29               CompTotal  What is your current total compensation (salar...
30                CompFreq   Is that compensation weekly, monthly, or yearly?
31           ConvertedComp  Salary converted to annual USD salaries using ...
32             WorkWeekHrs   On average, how many hours per week do you work?
33                WorkPlan            How structured or planned is your work?
34           WorkChallenge  Of these options, what are your greatest chall...
35              WorkRemote                    How often do you work remotely?
36                 WorkLoc                    Where would you prefer to work?
37                  ImpSyn  For the specific work you do, and the years of...
38                 CodeRev           Do you review code as part of your work?
39              CodeRevHrs  On average, how many hours per week do you spe...
40               UnitTests  Does your company regularly employ unit tests ...
41             PurchaseHow  How does your company make decisions about pur...
42            PurchaseWhat  What level of influence do you, personally, ha...
43      LanguageWorkedWith  Which of the following programming, scripting,...
44  LanguageDesireNextYear  Which of the following programming, scripting,...
45      DatabaseWorkedWith  Which of the following database environments h...
46  DatabaseDesireNextYear  Which of the following database environments h...
47      PlatformWorkedWith  Which of the following platforms have you done...
48  PlatformDesireNextYear  Which of the following platforms have you done...
49      WebFrameWorkedWith  Which of the following web frameworks have you...
50  WebFrameDesireNextYear  Which of the following web frameworks have you...
51      MiscTechWorkedWith  Which of the following other frameworks, libra...
52  MiscTechDesireNextYear  Which of the following other frameworks, libra...
53              DevEnviron  Which development environment(s) do you use re...
54                   OpSys  What is the primary operating system in which ...
55              Containers  How do you use containers (Docker, Open Contai...
56           BlockchainOrg  How is your organization thinking about or imp...
57            BlockchainIs  Blockchain / cryptocurrency technology is prim...
58              BetterLife  Do you think people born today will have a bet...
59                ITperson   Are you the "IT support person" for your family?
60                   OffOn        Have you tried turning it off and on again?
61             SocialMedia        What social media site do you use the most?
62            Extraversion    Do you prefer online chat or IRL conversations?
63              ScreenName                               What do you call it?
64              SOVisit1st  To the best of your memory, when did you first...
65             SOVisitFreq  How frequently would you say you visit Stack O...
66               SOVisitTo  I visit Stack Overflow to... (check all that a...
67            SOFindAnswer  On average, how many times a week do you find ...
68             SOTimeSaved  Think back to the last time you solved a codin...
69           SOHowMuchTime  About how much time did you save? If you're no...
70               SOAccount              Do you have a Stack Overflow account?
71              SOPartFreq  How frequently would you say you participate i...
72                  SOJobs  Have you ever used or visited Stack Overflow J...
73                EntTeams  Have you ever used Stack Overflow for Enterpri...
74                  SOComm  Do you consider yourself a member of the Stack...
75           WelcomeChange  Compared to last year, how welcome do you feel...
76            SONewContent  Would you like to see any of the following on ...
77                     Age  What is your age (in years)? If you prefer not...
78                  Gender  Which of the following do you currently identi...
79                   Trans                    Do you identify as transgender?
80               Sexuality  Which of the following do you currently identi...
81               Ethnicity  Which of the following do you identify as? Ple...
82              Dependents  Do you have any dependents (e.g., children, el...
83            SurveyLength  How do you feel about the length of the survey...
84              SurveyEase  How easy or difficult was this survey to compl...

In [13]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,84334,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Germany,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,500 to 999 employees,"Developer, full-stack",4,17,3,Slightly satisfied,Slightly dissatisfied,Not at all confident,Yes,No,I am actively looking for a job,3-4 years ago,Write any code,Yes,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,EUR,European Euro,36000.0,Yearly,41247.0,40.0,There is a schedule and/or spec (made by me or...,Lack of support from management,Less than once per month / Never,Home,Average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScript,HTML/CSS;JavaScript,PostgreSQL,PostgreSQL,MacOS,AWS;MacOS;Windows,ASP.NET;jQuery;React.js;Spring;Vue.js,React.js;Spring;Vue.js,NaN,NaN,Android Studio;IntelliJ;Visual Studio;Visual S...,Windows,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,Yes,Yes,Reddit,Online,Username,NaN,A few times per month or weekly,Get a sense of belonging to the developer comm...,1-2 times per week,The other resource was much faster,0-10 minutes,Yes,A few times per week,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers,26.0,Man,No,Straight / Heterosexual,NaN,No,Too long,Easy
1,14662,I am a student who is learning to code,Yes,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Sri Lanka,"Yes, full-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,NaN,"Developer, front-end;Developer, full-stack;Dev...",5,14,NaN,NaN,NaN,NaN,NaN,NaN,I am not interested in new job opportunities,Less than a year ago,NaN,NaN,"Languages, frameworks, and other technologies ...",I was preparing for a job search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;PHP;TypeScript,Dart;HTML/CSS;Java;JavaScript;TypeScript,Firebase;MongoDB;Microsoft SQL Server;MySQL,Firebase;MongoDB;Microsoft SQL Server;MySQL,NaN,NaN,Angular/Angular.js;React.js;Vue.js,Angular/Angular.js;React.js;Vue.js,Node.js;React Native,Flutter;Node.js;React Native,Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,WhatsApp,In real life (in person),Username,2016,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers,20.0,Woman,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Neither easy nor difficult
2,3292,I am a student who is learning to code,No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Sweden,"Yes, part-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...",NaN,NaN,Student,4,17,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",1-2 years ago,NaN,NaN,Industry that I'd be working in;Remote work op...,I was preparing for a job search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Python,Python,MongoDB,MongoDB,MacOS,MacOS,NaN,NaN,NaN,NaN,Visual Studio Code,MacOS,I do not use containers,NaN,NaN,Yes,Yes,What?,YouTube,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,25.0,Man,No,Straight / Heterosexual,Multiracial,No,Too long,Easy
3,36271,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United Kingdom,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,20 to 99 employees,"Developer, back-end;Developer, desktop or ente...",13,11,3,Very satisfied,Very satisfied,Very confident,Yes,Not sure,I am not interested in new job opportunities,1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,GBP,Pound sterling,30000.0,Yearly,39254.0,38.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",3.0,"Yes, it's not part of our process but the deve...",Developers and management have nearly equal in...,I have little or no influence,Bash/Shell/PowerShell;C#;Java;SQL,Bash/Shell/PowerShell;C#;Erlang;Go;SQL,Elasticsearch;Microsoft SQL Server;Redis;SQLit...,Cassandra;Microsoft SQL Server;Redis;SQLite;Ot...,Docker;Kubernetes;Linux;Microsoft Azure;Windows,Docker;Kubernetes;Linux;Microsoft Azure;Raspbe...,ASP.NET,ASP.NET,.NET;.NET Core,.NET;.NET Core,Visual Studio;Visual Studio Code,Windows,Development;Testing;Production;Outside of work...,Not at all,A passing fad,No,Yes,Yes,I don't use social media,In real life (in person),NaN,2011,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not at all",Just as welcome now as I felt last year,Tech articles written by other developers,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,32292,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",20 to 99 employees,"Developer, back-end;Developer, front-end;Devel...",6,15,1,Slightly satisfied,Slightly satisfied,Somewhat confident,No,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,Write any code;Interview with people in senior...,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,INR,Indian rupee,20000.0,Monthly,3360.0,16.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Not enoug...,A few days each month,Office,A little above average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Python;SQL,C++;Java;Python;R;Scala;SQL;TypeScript,MySQL,DynamoDB;Firebase;MongoDB;MySQL;Oracle;PostgreSQL,Linux,Arduino;Linux;Raspberry Pi;Slack,Django;jQuery,Angular/Angular.js;Django;jQuery;React.js,NaN,Apache Spark;Pandas,PyCharm,Linux-based,I do not use containers,Not at all,NaN,No,"Fortunately, someone else has that title",Yes,Facebook,In real life (in person),Username,2017,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, somewhat",Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,23.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [14]:
df.tail()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
44436,8766,I code primarily as a hobby,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",Russian Federation,"Yes, part-time",Some college/university study without earning ...,Web development or web design,Taken an online course in programming or softw...,NaN,"Developer, front-end;Student",1,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Python,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;K...,NaN,MongoDB;MySQL;PostgreSQL,Heroku;Windows,Docker;Heroku;Linux;Raspberry Pi;Windows,Django;Flask,Django;Flask,NaN,NaN,IPython / Jupyter;Visual Studio Code,Windows,I do not use containers,NaN,NaN,Yes,Yes,Yes,NaN,Online,Login,2016,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,31-60 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
44437,72435,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","10,000 or more employees","Developer, back-end",15,23,15,Slightly satisfied,Slightly satisfied,Not at all confident,No,No,I am actively looking for a job,More than 4 years ago,Interview with people in peer roles;Interview ...,No,Remote work options;Diversity of the company o...,I had a negative experience or interaction at ...,USD,United States dollar,130000.0,Yearly,130000.0,40.0,There's no schedule or spec; I work on what se...,Lack of support from management;Time spent com...,Less than once per month / Never,Home,Average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Not sure,I have little or no influence,HTML/CSS;Java;JavaScript;SQL;TypeScript,Clojure;Go;Java;JavaScript;Kotlin;Python;Ruby;...,MySQL;Oracle;PostgreSQL;SQLite,Cassandra;Elasticsearch;MongoDB;Redis;SQLite,Android;Docker;Linux;MacOS,Android;Docker;Kubernetes;Linux;MacOS,Spring,Angular/Angular.js;Spring;Vue.js,Hadoop,Ansible;Hadoop;Node.js,Atom;Eclipse;IntelliJ;RubyMine;Sublime Text;Te...,MacOS,Development;Testing;Production,NaN,NaN,Yes,SIGH,No,YouTube,In real life (in person),Username,2015,I have never visited Stack Overflow (before to...,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,NaN,NaN,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,40.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Easy
44438,34292,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...","Designer;Developer, back-end;Developer, deskto...",40,NaN,40,Very satisfied,Very satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",NA - I am an independent contractor or self em...,"Write code by hand (e.g., on a whiteboard)",No,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",USD,United States dollar,NaN,NaN,NaN,NaN,There is a schedule and/or spec (made by me or...,Inadequate access to necessary tools;Meetings;...,"More than half, but not all, the time",Home,Far above average,"Yes, because I see value in code review",NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;JavaScrip...,Bash/Shell/PowerShell;C;C++;HTML/CSS;JavaScrip...,MySQL;Oracle;PostgreSQL,PostgreSQL,Linux;Windows,Linux;Windows,NaN,jQuery,NaN,NaN,Eclipse;Sublime Text;Vim,Windows,I do not use containers,NaN,An irresponsible use of resources,No,Yes,What?,YouTube,Online,Login,NaN,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,They were about the same,NaN,Yes,A few times per month or weekly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,NaN,NaN,NaN,NaN,NaN,No,Too long,Easy
44439,14219,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Norway,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...","Taught yourself a new language, framework, or ...",2-9 employees,"Developer, full-stack",8,14,3,Slightly satisfied,Neither satisfied nor dissatisfied,Not at all confident,No,No,"I’m not actively looking, but I am open to new...",3-4 years ago,Interview with people in peer roles;Interview ...,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,NOK,Norwegian krone,600000.0,Yearly,71097.0,42.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Lack of...,Less than once per month / Never,Office,Far above average,No,NaN,"Yes, it's part of our process",NaN,I have a great deal of influence,HTML/CSS;JavaScript;SQL,Go;TypeScript;WebAssembly,MySQL;Other(s):,MySQL;Other(s):,AWS;Linux,AWS;Linux,jQuery,Vue.js,Node.js,Node.js,Visual Studio Code,MacOS,I do not use containers,Not at all,NaN,No,SIGH,Yes,Facebook,Online,Username,I don't remember,Multiple times per day,Find answers to specific questions,6-10 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech meetups or events in your area,28.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
44440,64515,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Received on-the-job training in software devel...,20 to 99 employees,"Developer, full-stack;Developer, mobile",14,10,5,Very satisfied,Very satisfied,Somewhat confident,Not sure,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,USD,United States dollar,87000.0,Yearly,87000.0,45.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,A few days each month,Home,A little above average,"Yes, because I see value in code review",2.0,"No, but I think we should",NaN,I have some influence,C#;HTML/CSS;JavaScript;PHP;SQL;TypeScript,C#;HTML/CSS;JavaScript;Kotlin;PHP;Python;SQL;S...,MariaDB;Microsoft SQL Server;MySQL;SQLite,Microsoft SQL Server;MySQL;SQLite,iOS,Android;Heroku;iOS,Angular/Angular.js;ASP.NET;jQuery;Laravel,Angular/Angular.js;ASP.NET;jQuery;Laravel;Vue.js,.NET;.NET Core;Node.js;Xamarin,Flutter;.NET;.NET Core;Node.js;Pandas;TensorFlow,Visual Studio;Visual Studio Code,MacOS,I do not use containers,Not at all,Useful across many domains and could change ma...,Yes,Yes,Yes,Reddit,Online,Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,31.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy

In [15]:

data = {
    "first_name": ["Rahul", "Amit", "Priya", "Sneha", "Rohan"],
    "last_name": ["Sharma", "Patil", "Deshmukh", "Joshi", "Verma"],
    "email": [
        "rahul.sharma@example.com",
        "amit.patil@example.com",
        "priya.deshmukh@example.com",
        "sneha.joshi@example.com",
        "rohan.verma@example.com"
    ]
}

In [17]:
df1 = pd.DataFrame(data)
df1

  first_name last_name                       email
0      Rahul    Sharma    rahul.sharma@example.com
1       Amit     Patil      amit.patil@example.com
2      Priya  Deshmukh  priya.deshmukh@example.com
3      Sneha     Joshi     sneha.joshi@example.com
4      Rohan     Verma     rohan.verma@example.com

In [22]:
df1[["first_name"]]

  first_name
0      Rahul
1       Amit
2      Priya
3      Sneha
4      Rohan

In [23]:
df1[["first_name","email"]]

  first_name                       email
0      Rahul    rahul.sharma@example.com
1       Amit      amit.patil@example.com
2      Priya  priya.deshmukh@example.com
3      Sneha     sneha.joshi@example.com
4      Rohan     rohan.verma@example.com

In [29]:
df.iloc[[0, 1], 2]

0    Yes
1    Yes
Name: Hobbyist, dtype: str

In [32]:
df1.loc[[0, 1], ['email', 'last_name']]

                      email last_name
0  rahul.sharma@example.com    Sharma
1    amit.patil@example.com     Patil